/* tools-data.js — tool dataset as a global, so the explorer works when the
   site is opened directly as a local file (file://) without a web server.
   Velden: ease (gebruiksgemak 1-5), quality (kwaliteit 1-5), pros[], cons[], starter (optioneel). */
window.TOOLS_DATA = {
  "updated": "juni 2026",
  "tools": [
    { "name": "ChatGPT", "cat": "AI-assistenten", "level": 1, "ease": 5, "quality": 5, "price": "Gratis · Plus €20/mnd",
      "desc": "Meest gebruikte AI-assistent. Sterk in redeneren, agents, custom GPTs en beeldgeneratie.", "url": "https://chatgpt.com",
      "pros": ["Allrounder met groot ecosysteem", "Custom GPTs en Projects", "Sterke beeld- en spraakfuncties"],
      "cons": ["Kan vleierig (sycophant) zijn", "Beste functies achter betaalmuur"],
      "starter": "Je bent een ervaren marketingadviseur. Schrijf 3 varianten van een wervende e-mail voor [product] gericht op [doelgroep]. Toon: enthousiast maar zakelijk. Max. 150 woorden per variant, met onderwerp-regel." },
    { "name": "Claude", "cat": "AI-assistenten", "level": 1, "ease": 5, "quality": 5, "price": "Gratis · Pro €20/mnd",
      "desc": "Uitblinker in lange documenten, nauwkeurig redeneren en interactieve artifacts.", "url": "https://claude.ai",
      "pros": ["Top in lange documenten en analyse", "Artifacts: bouw direct werkende tools", "Sterke focus op veiligheid"],
      "cons": ["Soms minder beschikbaar bij piek", "Onduidelijke gebruikslimieten"],
      "starter": "Je bent een data-analist. Analyseer het bijgevoegde document en vat de 5 belangrijkste inzichten samen in een tabel met kolommen: inzicht, onderbouwing, en aanbevolen actie." },
    { "name": "Google Gemini", "cat": "AI-assistenten", "level": 1, "ease": 5, "quality": 4, "price": "Gratis · AI Pro €22/mnd",
      "desc": "Diep geïntegreerd in Google Workspace. Sterk in beeld- en videobegrip en zeer snelle modellen.", "url": "https://gemini.google.com",
      "pros": ["Naadloos in Gmail, Docs en Sheets", "Zeer snelle modellen", "Sterk multimodaal (beeld/video)"],
      "cons": ["Soms oppervlakkig", "Functies in gefaseerde uitrol"],
      "starter": "Vat deze Google Doc samen in 5 bullets en stel 3 verbeterpunten voor de structuur voor." },
    { "name": "Microsoft Copilot", "cat": "AI-assistenten", "level": 1, "ease": 4, "quality": 4, "price": "Gratis · M365 Copilot €22/mnd",
      "desc": "AI binnen Microsoft 365: Word, Excel, Outlook, Teams.", "url": "https://copilot.microsoft.com",
      "pros": ["Diepe Microsoft 365-integratie", "Sterk in Excel en Outlook", "Goede compliance-opties"],
      "cons": ["Beste waarde alleen binnen MS-suite", "Gratis versie beperkt"] },
    { "name": "Perplexity", "cat": "AI-assistenten", "level": 1, "ease": 5, "quality": 4, "price": "Gratis · Pro €20/mnd",
      "desc": "AI-zoekmachine met actuele resultaten en heldere bronvermelding.", "url": "https://perplexity.ai",
      "pros": ["Actuele info met bronnen", "Uitstekend voor research", "Ruime gratis versie"],
      "cons": ["Minder creatief", "Geen eigen kernmodel"],
      "starter": "Geef een actueel overzicht van [onderwerp] met de belangrijkste ontwikkelingen van het afgelopen jaar. Vermeld bij elk punt de bron." },
    { "name": "Mistral / Le Chat", "cat": "AI-assistenten", "level": 1, "ease": 4, "quality": 3, "price": "Gratis · Pro €15/mnd",
      "desc": "Europees alternatief met sterke meertaligheid en privacy-focus.", "url": "https://chat.mistral.ai",
      "pros": ["Europees, privacy-gericht", "Sterke meertaligheid", "Agents en document-analyse"],
      "cons": ["Kleiner ecosysteem", "Minder geavanceerd dan top-3"] },

    { "name": "Zapier", "cat": "Automatisering & agents", "level": 1, "ease": 5, "quality": 4, "price": "Gratis · vanaf €20/mnd",
      "desc": "8.000+ app-koppelingen en simpele AI-triggers.", "url": "https://zapier.com",
      "pros": ["Meeste integraties (8.000+)", "Heel laagdrempelig", "Veel kant-en-klare sjablonen"],
      "cons": ["Duurder bij hoog volume", "Minder maatwerk dan code-tools"] },
    { "name": "Make.com", "cat": "Automatisering & agents", "level": 2, "ease": 4, "quality": 5, "price": "Gratis · vanaf €9/mnd",
      "desc": "Visuele workflowbouwer met 2.500+ integraties.", "url": "https://make.com",
      "pros": ["Veel waarde voor je geld", "Krachtige visuele editor", "Herbruikbare scenario's"],
      "cons": ["Steilere leercurve dan Zapier", "Complexe flows worden snel groot"] },
    { "name": "Lindy AI", "cat": "Automatisering & agents", "level": 1, "ease": 5, "quality": 4, "price": "Gratis · vanaf €50/mnd",
      "desc": "AI-agents die je in gewone taal opzet voor e-mail, planning en support.", "url": "https://lindy.ai",
      "pros": ["Opzet in gewone taal", "Sterk voor e-mail en planning", "30+ talen"],
      "cons": ["Prijziger bij opschalen", "Minder fijnmazige controle"] },
    { "name": "n8n", "cat": "Automatisering & agents", "level": 3, "ease": 3, "quality": 5, "price": "Gratis (self-host) · vanaf €22/mnd",
      "desc": "Krachtigste open-source optie: eigen code-stappen, AI-agenttools en zelf te hosten.", "url": "https://n8n.io",
      "pros": ["Open source, zelf te hosten", "Eigen code-stappen mogelijk", "Sterke AI-agenttools"],
      "cons": ["Technischer in gebruik", "Self-hosting vraagt onderhoud"] },
    { "name": "Microsoft Power Automate", "cat": "Automatisering & agents", "level": 2, "ease": 3, "quality": 4, "price": "vanaf €15/mnd",
      "desc": "Diepe Microsoft 365-integratie, AI Builder en desktop-automatisering (RPA).", "url": "https://make.powerautomate.com",
      "pros": ["Diepe MS 365-integratie", "Desktop-RPA inbegrepen", "Robuuste compliance"],
      "cons": ["Op zijn best binnen Microsoft", "Interface kan complex zijn"] },
    { "name": "MindStudio", "cat": "Automatisering & agents", "level": 1, "ease": 5, "quality": 4, "price": "Gratis · €20–49/mnd",
      "desc": "100+ sjablonen en directe LLM-koppelingen. AI-apps bouwen zonder code.", "url": "https://mindstudio.ai",
      "pros": ["Zeer goede onboarding", "100+ sjablonen", "Direct LLM's koppelen"],
      "cons": ["Minder geschikt voor zware logica"] },
    { "name": "Gumloop", "cat": "Automatisering & agents", "level": 1, "ease": 5, "quality": 4, "price": "Gratis · tot €60/mnd",
      "desc": "Snelle drag-and-drop workflows voor niet-developers.", "url": "https://gumloop.com",
      "pros": ["Snel resultaat", "Drag-and-drop", "Voor niet-developers"],
      "cons": ["Minder maatwerk", "Jonger platform"] },
    { "name": "Relevance AI", "cat": "Automatisering & agents", "level": 2, "ease": 4, "quality": 4, "price": "Team vanaf €99/mnd",
      "desc": "Bouw je eigen AI-'workforce' van samenwerkende agents.", "url": "https://relevanceai.com",
      "pros": ["Multi-agent teams", "Sterk voor sales en data", "CRM-integratie"],
      "cons": ["Prijs loopt op bij teams"] },
    { "name": "Stack AI", "cat": "Automatisering & agents", "level": 2, "ease": 4, "quality": 4, "price": "Gratis · Enterprise op aanvraag",
      "desc": "Kennisbanken, RAG en API's met sterke teamsamenwerking.", "url": "https://stack-ai.com",
      "pros": ["Sterke RAG/kennisbanken", "Goed schaalbaar", "Teamsamenwerking"],
      "cons": ["Enterprise-prijs onduidelijk"] },
    { "name": "Voiceflow", "cat": "Automatisering & agents", "level": 2, "ease": 4, "quality": 4, "price": "Gratis · vanaf €49/mnd",
      "desc": "Visuele bouwer voor voice- en chatbots over meerdere kanalen.", "url": "https://voiceflow.com",
      "pros": ["Sterk voor chat- en voicebots", "Omnichannel", "Visuele flows"],
      "cons": ["Niche-focus op bots"] },
    { "name": "Flowise", "cat": "Automatisering & agents", "level": 3, "ease": 2, "quality": 3, "price": "Gratis (OSS) · €35+/mnd",
      "desc": "Open-source LLM/RAG-workflows met vector-databases.", "url": "https://flowiseai.com",
      "pros": ["Open source", "Vector-databases", "Voor zelf-hosters"],
      "cons": ["Voor developers", "Beperkte support"] },
    { "name": "Dust", "cat": "Automatisering & agents", "level": 3, "ease": 3, "quality": 4, "price": "Prijs op aanvraag",
      "desc": "Enterprise-platform voor AI-agents met SOC2+ en fijnmazige controle.", "url": "https://dust.tt",
      "pros": ["Enterprise-schaal", "Sterke compliance (SOC2+)", "Fijnmazige controle"],
      "cons": ["Gericht op grote organisaties"] },

    { "name": "Lovable", "cat": "App bouwen (vibecoding)", "level": 1, "ease": 5, "quality": 5, "price": "Gratis · vanaf €22/mnd",
      "desc": "Beste startpunt voor niet-technische bouwers. Nette React-code met database (Supabase).", "url": "https://lovable.dev",
      "pros": ["Beste keuze voor niet-technici", "Nette code + database", "Snel van idee naar app"],
      "cons": ["Minder controle dan een echte editor"],
      "starter": "Bouw een eenvoudige web-app waarmee ik klantverzoeken kan bijhouden. Met een formulier (naam, verzoek, prioriteit) en een overzichtslijst die ik kan filteren op status. Strak, modern design." },
    { "name": "Bolt.new", "cat": "App bouwen (vibecoding)", "level": 2, "ease": 4, "quality": 4, "price": "Gratis · vanaf €18/mnd",
      "desc": "Snelle in-browser app-bouwer met steun voor veel frameworks.", "url": "https://bolt.new",
      "pros": ["Snel prototypen in de browser", "Veel frameworks", "Goede controle"],
      "cons": ["Verbruik (tokens) loopt op", "Prototypes, geen productie"],
      "starter": "Maak een prototype van een landingspagina voor [dienst] met een hero-sectie, 3 voordelen, prijskaarten en een contactformulier." },
    { "name": "v0 (Vercel)", "cat": "App bouwen (vibecoding)", "level": 2, "ease": 4, "quality": 4, "price": "Gratis · vanaf €18/mnd",
      "desc": "Genereert mooie Next.js-interfaces en losse UI-componenten.", "url": "https://v0.dev",
      "pros": ["Zeer strak design", "Sterk voor UI-componenten", "Next.js + database"],
      "cons": ["Vooral front-end gericht"],
      "starter": "Ontwerp een modern dashboard-component met statistiek-kaarten bovenaan en een tabel eronder. Donker thema, afgeronde hoeken." },
    { "name": "Replit Agent", "cat": "App bouwen (vibecoding)", "level": 2, "ease": 4, "quality": 4, "price": "Gratis · vanaf €18/mnd",
      "desc": "Meest autonome bouwer: code, database, hosting en deploy in één plek.", "url": "https://replit.com",
      "pros": ["Alles-in-één (incl. hosting)", "Meest autonoom", "30+ integraties"],
      "cons": ["Iets meer een ontwikkelomgeving"],
      "starter": "Bouw en publiceer een kleine web-app die een wekelijkse nieuwsbrief-tekst genereert op basis van een paar invoervelden." },
    { "name": "Claude (artifacts/code)", "cat": "App bouwen (vibecoding)", "level": 1, "ease": 5, "quality": 5, "price": "Gratis · Pro €20/mnd",
      "desc": "Bouw direct werkende tools en visualisaties in een gesprek.", "url": "https://claude.ai",
      "pros": ["Laagdrempeligste start", "Werkende tool in een chat", "Geen account bij extra dienst nodig"],
      "cons": ["Eén bestand, beperkte schaal"],
      "starter": "Bouw een interactieve rekentool waarmee ik de tijdsbesparing van een geautomatiseerde taak kan berekenen (uren per week × uurtarief). Toon het resultaat per maand en jaar." },
    { "name": "Cursor", "cat": "App bouwen (vibecoding)", "level": 4, "ease": 2, "quality": 5, "price": "Gratis · Pro €18/mnd",
      "desc": "AI-pair-programmer in een echte code-editor.", "url": "https://cursor.com",
      "pros": ["Volledige controle", "Begrijpt je hele codebase", "Multi-file bewerkingen"],
      "cons": ["Voor wie al wat programmeert", "Echte editor, hogere leercurve"] }
  ]
};
